### ISSUE TITLE
Add mmol

### ISSUE THREAD

**Issue by many7695** [nielsmaerten/glucose-ticker#6]
Can u add mmol/l for Canadian users, thank u, I love both of the these projects this one and your google assistant

**Comment by nielsmaerten** [comment]
Hi @many7695 

I've just published an early alpha of version 0.4.0, which has support for mmol/l. Here's what it looks like:
![screenshot](https://i.imgur.com/Vvdnbf7.png)

You can now download v0.4.0-alpha.2 from the [releases](https://github.com/nielsmaerten/glucose-ticker/releases) page.  
It's an alpha, so things still look a bit rough, but the basic functionality should work fine.

Hope you like it ;)
